<a href="https://colab.research.google.com/github/Luca-1221/MyMIS433/blob/main/Copy_of_assignment_IMDB_manipulation_summarization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [ ]:
import pandas as pd
import numpy as np

To read the data file from your Google Drive, mount your drive first.

In [27]:
from google.colab import drive
drive.mount('/content/drive')
pd.read_csv("/content/imdb_top_1000 (2).csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://m.media-amazon.com/images/M/MV5BNGEwMT...,Breakfast at Tiffany's,1961,A,115 min,"Comedy, Drama, Romance",7.6,A young New York socialite becomes interested ...,76.0,Blake Edwards,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen,166544,NaN
996,https://m.media-amazon.com/images/M/MV5BODk3Yj...,Giant,1956,G,201 min,"Drama, Western",7.6,Sprawling epic covering the life of a Texas ca...,84.0,George Stevens,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker,34075,NaN
997,https://m.media-amazon.com/images/M/MV5BM2U3Yz...,From Here to Eternity,1953,Passed,118 min,"Drama, Romance, War",7.6,"In Hawaii in 1941, a private is cruelly punish...",85.0,Fred Zinnemann,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed,43374,"30,500,000"
998,https://m.media-amazon.com/images/M/MV5BZTBmMj...,Lifeboat,1944,NaN,97 min,"Drama, War",7.6,Several survivors of a torpedoed merchant ship...,78.0,Alfred Hitchcock,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix,26471,NaN
999,https://m.media-amazon.com/images/M/MV5BMTY5OD...,The 39 Steps,1935,NaN,86 min,"Crime, Mystery, Thriller",7.6,A man in London tries to help a counter-espion...,93.0,Alfred Hitchcock,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle,51853,NaN

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
# Read the data file 'imdb_top_1000 (2).csv' to a dataframe named 'imdb'
imdb = pd.read_csv('/content/imdb_top_1000 (2).csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [24]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [25]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [26]:
# Display top 10 movies' title, released year and IMDB rating.
movies = imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']]
movies.head(10)

                                    Series_Title Released_Year  IMDB_Rating
0                       The Shawshank Redemption          1994          9.3
1                                  The Godfather          1972          9.2
2                                The Dark Knight          2008          9.0
3                         The Godfather: Part II          1974          9.0
4                                   12 Angry Men          1957          9.0
5  The Lord of the Rings: The Return of the King          2003          8.9
6                                   Pulp Fiction          1994          8.9
7                               Schindler's List          1993          8.9
8                                      Inception          2010          8.8
9                                     Fight Club          1999          8.8

In [30]:
# Display movies ranked 11-20.
# Show their title, released year and IMDB ratinngs
imdb[['Series_Title', 'Released_Year', 'IMDB_Rating']].iloc[10:20]

,Series_Title,Released_Year,IMDB_Rating
10,The Lord of the Rings: The Fellowship of the Ring,2001,8.8
11,Forrest Gump,1994,8.8
12,"Il buono, il brutto, il cattivo",1966,8.8
13,The Lord of the Rings: The Two Towers,2002,8.7
14,The Matrix,1999,8.7
15,Goodfellas,1990,8.7
16,Star Wars: Episode V - The Empire Strikes Back,1980,8.7
17,One Flew Over the Cuckoo's Nest,1975,8.7
18,Hamilton,2020,8.6
19,Gisaengchung,2019,8.6

In [31]:
# Select all movies directed by Quentin Tarantino.
# Show their title, released year, IMDB rating, and gross.
Tarantino = imdb[imdb['Director'] == 'Quentin Tarantino']
Tarantino[['Series_Title', 'Released_Year', 'IMDB_Rating', 'Gross']]

                         Series_Title Released_Year  IMDB_Rating        Gross
6                        Pulp Fiction          1994          8.9  107,928,762
62                   Django Unchained          2012          8.4  162,805,434
93               Inglourious Basterds          2009          8.3  120,540,719
103                    Reservoir Dogs          1992          8.3    2,832,029
241                 Kill Bill: Vol. 1          2003          8.1   70,099,045
369                 Kill Bill: Vol. 2          2004          8.0   66,208,183
584                 The Hateful Eight          2015          7.8   54,117,416
879  Once Upon a Time... in Hollywood          2019          7.6  142,502,728

In [33]:
# Select all R rated movies with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
r_rated_high = imdb[(imdb['Certificate'] == 'R') & (imdb['IMDB_Rating'] >= 8.5)]
r_rated_high[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

           Series_Title Released_Year Certificate  IMDB_Rating
24  Saving Private Ryan          1998           R          8.6
38          The Pianist          2002           R          8.5
40   American History X          1998           R          8.5

In [36]:
# How many unique values are there in the column "Released_Year"?
# Hint: nunique()
imdb['Released_Year'].nunique()

100

In [37]:
# Count the number of movies in each "Released_Year"?
# Hint: value_counts()
imdb['Released_Year'].value_counts()

Released_Year
2014    32
2004    31
2009    29
2013    28
2016    28
        ..
1920     1
1930     1
1922     1
1943     1
PG       1
Name: count, Length: 100, dtype: int64

In [41]:
# In this dataset, there is a movie with an error in "Released_Year".
# Hint: Released_Year should be a 4-digit integer but this movie's is not.
# Find this movie.
error_movie = imdb[~imdb['Released_Year'].str.isnumeric()]
error_movie

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [43]:
# Correct the values for the corresponding columns ("Released_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular row by: df.loc[row_name, column_name] = new_value
index_to_fix = error_movie.index[0]
imdb.loc[index_to_fix, 'Released_Year'] = '1995'
imdb.loc[index_to_fix, 'Certificate'] = 'PG'

In [45]:
# Change the data type of "Released_Year" to int
imdb['Released_Year'] = imdb['Released_Year'].astype(int)

In [46]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, certificate, and IMDB rating.
modern_hits = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
modern_hits[['Series_Title', 'Released_Year', 'Certificate', 'IMDB_Rating']]

        Series_Title  Released_Year Certificate  IMDB_Rating
8          Inception           2010          UA          8.8
18          Hamilton           2020       PG-13          8.6
19      Gisaengchung           2019           A          8.6
20   Soorarai Pottru           2020           U          8.6
21      Interstellar           2014          UA          8.6
33             Joker           2019           A          8.5
34          Whiplash           2014           A          8.5
35  The Intouchables           2011          UA          8.5

In [61]:
# Select all movies whose genres contain 'Animation'
imdb[imdb['Genre'].str.contains('Animation')]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
23,https://m.media-amazon.com/images/M/MV5BMjlmZm...,Sen to Chihiro no kamikakushi,2001,U,125 min,"Animation, Adventure, Family",8.6,"During her family's move to the suburbs, a sul...",96.0,Hayao Miyazaki,Daveigh Chase,Suzanne Pleshette,Miyu Irino,Rumi Hiiragi,651376,10055859.0
43,https://m.media-amazon.com/images/M/MV5BYTYxNG...,The Lion King,1994,U,88 min,"Animation, Adventure, Drama",8.5,Lion prince Simba and his father are targeted ...,88.0,Roger Allers,Rob Minkoff,Matthew Broderick,Jeremy Irons,James Earl Jones,942045,422783777.0
46,https://m.media-amazon.com/images/M/MV5BZmY2Nj...,Hotaru no haka,1988,U,89 min,"Animation, Drama, War",8.5,A young boy and his little sister struggle to ...,94.0,Isao Takahata,Tsutomu Tatsumi,Ayano Shiraishi,Akemi Yamaguchi,Yoshiko Shinohara,235231,NaN
56,https://m.media-amazon.com/images/M/MV5BODRmZD...,Kimi no na wa.,2016,U,106 min,"Animation, Drama, Fantasy",8.4,Two strangers find themselves linked in a biza...,79.0,Makoto Shinkai,Ryûnosuke Kamiki,Mone Kamishiraishi,Ryô Narita,Aoi Yûki,194838,5017246.0
58,https://m.media-amazon.com/images/M/MV5BMjMwND...,Spider-Man: Into the Spider-Verse,2018,U,117 min,"Animation, Action, Adventure",8.4,Teen Miles Morales becomes the Spider-Man of h...,87.0,Bob Persichetti,Peter Ramsey,Rodney Rothman,Shameik Moore,Jake Johnson,375110,190241310.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,https://m.media-amazon.com/images/M/MV5BODkxNG...,Mulan,1998,U,88 min,"Animation, Adventure, Family",7.6,"To save her father from death in the army, a y...",71.0,Tony Bancroft,Barry Cook,Ming-Na Wen,Eddie Murphy,BD Wong,256906,120620254.0
971,https://m.media-amazon.com/images/M/MV5BMTY5Nj...,Omohide poro poro,1991,U,118 min,"Animation, Drama, Romance",7.6,A twenty-seven-year-old office worker travels ...,90.0,Isao Takahata,Miki Imai,Toshirô Yanagiba,Yoko Honna,Mayumi Izuka,27071,453243.0
976,https://m.media-amazon.com/images/M/MV5BN2JlZT...,The Little Mermaid,1989,U,83 min,"Animation, Family, Fantasy",7.6,A mermaid princess makes a Faustian bargain in...,88.0,Ron Clements,John Musker,Jodi Benson,Samuel E. Wright,Rene Auberjonois,237696,111543479.0
986,https://m.media-amazon.com/images/M/MV5BMzZiOD...,Watership Down,1978,U,91 min,"Animation, Adventure, Drama",7.6,Hoping to escape destruction by human develope...,64.0,Martin Rosen,John Hubley,John Hurt,Richard Briers,Ralph Richardson,33656,NaN
992,https://m.media-amazon.com/images/M/MV5BMjAwMT...,The Jungle Book,1967,U,78 min,"Animation, Adventure, Family",7.6,Bagheera the Panther and Baloo the Bear have a...,65.0,Wolfgang Reitherman,Phil Harris,Sebastian Cabot,Louis Prima,Bruce Reitherman,166409,141843612.0

In [62]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']].copy()

In [63]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']].copy()

In [65]:
# Sorting:
# Sort dataframe genres in ascending order of "Released_Year"
genres.sort_values(by='Released_Year')

                     Series_Title  Released_Year                         Genre
321  Das Cabinet des Dr. Caligari           1920      Fantasy, Horror, Mystery
127                       The Kid           1921         Comedy, Drama, Family
568                     Nosferatu           1922               Fantasy, Horror
194                  Sherlock Jr.           1924       Action, Comedy, Romance
193                 The Gold Rush           1925      Adventure, Comedy, Drama
..                            ...            ...                           ...
612    The Trial of the Chicago 7           2020      Drama, History, Thriller
613                          Druk           2020                 Comedy, Drama
20                Soorarai Pottru           2020                         Drama
18                       Hamilton           2020     Biography, Drama, History
205                          Soul           2020  Animation, Adventure, Comedy

[1000 rows x 3 columns]

In [71]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
filtered_imdb = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
filtered_imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values('Gross', ascending=False)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem?

In [76]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe
# The 'Gross' column has already been converted to a float type, so the string replacement is no longer needed.
# We can confirm its data type.
imdb['Gross'].dtype

dtype('float64')

In [89]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
filtered_imdb = imdb[(imdb['Released_Year'] >= 2010) & (imdb['IMDB_Rating'] >= 8.5)]
print(filtered_imdb[['Series_Title', 'Released_Year', 'Certificate', 'Gross']].sort_values('Gross', ascending=False))

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [79]:
# Add a new column "Runtime_min" by removing the substring " min" in "Runtime"
# Set its data type as int
# Hint: https://stackoverflow.com/questions/36505847/substring-of-an-entire-column-in-pandas-dataframe
imdb['Runtime_min'] = imdb['Runtime'].str.replace(' min', '').astype(int)

In [80]:
# Add a new column "Age_Year" by expression: Current year - Released_Year
from datetime import datetime
current_year = datetime.now().year
imdb['Age_Year'] = current_year - imdb['Released_Year']

In [82]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = (imdb['Released_Year'] // 10) * 10
filtered_imdb

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
8,https://m.media-amazon.com/images/M/MV5BMjAxMz...,Inception,2010,UA,148 min,"Action, Adventure, Sci-Fi",8.8,A thief who steals corporate secrets through t...,74.0,Christopher Nolan,Leonardo DiCaprio,Joseph Gordon-Levitt,Elliot Page,Ken Watanabe,2067042,292576195.0
18,https://m.media-amazon.com/images/M/MV5BNjViNW...,Hamilton,2020,PG-13,160 min,"Biography, Drama, History",8.6,The real life of one of America's foremost fou...,90.0,Thomas Kail,Lin-Manuel Miranda,Phillipa Soo,Leslie Odom Jr.,Renée Elise Goldsberry,55291,NaN
19,https://m.media-amazon.com/images/M/MV5BYWZjMj...,Gisaengchung,2019,A,132 min,"Comedy, Drama, Thriller",8.6,Greed and class discrimination threaten the ne...,96.0,Bong Joon Ho,Kang-ho Song,Lee Sun-kyun,Cho Yeo-jeong,Choi Woo-sik,552778,53367844.0
20,https://m.media-amazon.com/images/M/MV5BOTc2ZT...,Soorarai Pottru,2020,U,153 min,Drama,8.6,"Nedumaaran Rajangam ""Maara"" sets out to make t...",NaN,Sudha Kongara,Suriya,Madhavan,Paresh Rawal,Aparna Balamurali,54995,NaN
21,https://m.media-amazon.com/images/M/MV5BZjdkOT...,Interstellar,2014,UA,169 min,"Adventure, Drama, Sci-Fi",8.6,A team of explorers travel through a wormhole ...,74.0,Christopher Nolan,Matthew McConaughey,Anne Hathaway,Jessica Chastain,Mackenzie Foy,1512360,188020017.0
33,https://m.media-amazon.com/images/M/MV5BNGVjNW...,Joker,2019,A,122 min,"Crime, Drama, Thriller",8.5,"In Gotham City, mentally troubled comedian Art...",59.0,Todd Phillips,Joaquin Phoenix,Robert De Niro,Zazie Beetz,Frances Conroy,939252,335451311.0
34,https://m.media-amazon.com/images/M/MV5BOTA5ND...,Whiplash,2014,A,106 min,"Drama, Music",8.5,A promising young drummer enrolls at a cut-thr...,88.0,Damien Chazelle,Miles Teller,J.K. Simmons,Melissa Benoist,Paul Reiser,717585,13092000.0
35,https://m.media-amazon.com/images/M/MV5BMTYxND...,The Intouchables,2011,UA,112 min,"Biography, Comedy, Drama",8.5,After he becomes a quadriplegic from a paragli...,57.0,Olivier Nakache,Éric Toledano,François Cluzet,Omar Sy,Anne Le Ny,760360,13182281.0

## Part 2: Data Summarization

In [84]:
# Total "Gross" of all top 1000 movies
total_gross = imdb['Gross'].sum()
total_gross

np.float64(56536877976.0)

In [85]:
# Average "No_of_Votes" of all movies
avg_votes = imdb['No_of_Votes'].mean()
avg_votes

np.float64(273692.911)

In [86]:
# Count movies in each decade (e.g., ..., 1980, 1990, 2000, 2010, 2020)
# Sort decades by the number of movies in descending order
imdb['Decade'].value_counts().sort_index(ascending=False)

Decade
2020      6
2010    242
2000    237
1990    151
1980     89
1970     76
1960     73
1950     56
1940     35
1930     24
1920     11
Name: count, dtype: int64

In [87]:
# Count movies by different directors.
# Show the top 10 directors with the most movies in this list
imdb['Director'].value_counts().head(10)

Director
Alfred Hitchcock     14
Steven Spielberg     13
Hayao Miyazaki       11
Akira Kurosawa       10
Martin Scorsese      10
Woody Allen           9
Stanley Kubrick       9
Billy Wilder          9
Clint Eastwood        8
Christopher Nolan     8
Name: count, dtype: int64

In [90]:
# For each director, calculate the number of movies, average IMDB_Rating, and total gross.
# Ranked in descending order of total gross
# Show the top 10 directors with the most gross
director_summary = imdb.groupby('Director').agg(
    num_movies=('Series_Title', 'count'),
    average_IMDB_Rating=('IMDB_Rating', 'mean'),
    total_gross=('Gross', 'sum')
)
director_summary.sort_values('total_gross', ascending=False).head(10)

                   num_movies  average_IMDB_Rating   total_gross
Director
Steven Spielberg           13             8.030769  2.478133e+09
Anthony Russo               4             8.075000  2.205039e+09
Christopher Nolan           8             8.462500  1.937454e+09
James Cameron               5             8.080000  1.748237e+09
Peter Jackson               5             8.400000  1.597312e+09
J.J. Abrams                 3             7.833333  1.423171e+09
Brad Bird                   4             7.900000  1.099628e+09
Robert Zemeckis             5             8.120000  1.049446e+09
David Yates                 3             7.800000  9.789537e+08
Pete Docter                 4             8.125000  9.393821e+08

In [95]:
# Group movies by decade and director
# In each group (i.e., for each decade and each director),
# calculate the number of movies and average IMDB rating.
# Sort in descending order of movie count
director_decade_summary = imdb.groupby(['Decade', 'Director']).agg(
    num_movies=('Series_Title', 'count'),
    average_IMDB_Rating=('IMDB_Rating', 'mean')
).sort_values('num_movies', ascending=False)
director_decade_summary

                             num_movies  average_IMDB_Rating
Decade Director
1950   Billy Wilder                   6             8.133333
       Akira Kurosawa                 5             8.260000
2010   Denis Villeneuve               5             7.980000
1950   Alfred Hitchcock               5             8.220000
1980   Steven Spielberg               5             7.980000
...                                 ...                  ...
2010   Tyler Nilson                   1             7.600000
       Umesh Shukla                   1             8.100000
       Vikas Bahl                     1             8.200000
       Vikramaditya Motwane           1             8.200000
       Vishal Bhardwaj                1             8.100000

[749 rows x 2 columns]

In [96]:
# Find the top 3 highest rated movies of each year since 2010.
# Show their released year, ranking, title, and IMDB_Rating.
# Sort them in descending order of year and ascending order of ranking
recent_movies = imdb[imdb['Released_Year'] >= 2010].copy()
top_3_movies_by_year = recent_movies.sort_values(['Released_Year', 'IMDB_Rating'], ascending=[False, False])
top_3_movies_by_year = top_3_movies_by_year.groupby('Released_Year').head(3)
top_3_movies_by_year[['Released_Year','Series_Title','IMDB_Rating']]

     Released_Year                       Series_Title  IMDB_Rating
18            2020                           Hamilton          8.6
20            2020                    Soorarai Pottru          8.6
205           2020                               Soul          8.1
19            2019                       Gisaengchung          8.6
33            2019                              Joker          8.5
59            2019                  Avengers: Endgame          8.4
53            2018                         Capharnaüm          8.4
58            2018  Spider-Man: Into the Spider-Verse          8.4
60            2018             Avengers: Infinity War          8.4
54            2017          Ayla: The Daughter of War          8.4
55            2017                       Vikram Vedha          8.4
61            2017                               Coco          8.4
56            2016                     Kimi no na wa.          8.4
57            2016                             Dangal          8.4
196           2016                               Pink          8.1
133           2015                             Talvar          8.2
136           2015                           Drishyam          8.2
203           2015                               Room          8.1
21            2014                       Interstellar          8.6
34            2014                           Whiplash          8.5
200           2014                              Mommy          8.1
87            2013                           Drishyam          8.3
137           2013                              Queen          8.2
138           2013                        Mandariinid          8.2
62            2012                   Django Unchained          8.4
63            2012              The Dark Knight Rises          8.4
88            2012                             Jagten          8.3
35            2011                   The Intouchables          8.5
89            2011            Jodaeiye Nader az Simin          8.3
144           2011                            Warrior          8.2
8             2010                          Inception          8.8
90            2010                          Incendies          8.3
141           2010                              Udaan          8.2

In [99]:
# Find all directors whose movies appeared in at least five different decades.
# Your result should include: director, decade, and the number of movies in the decade.
longevity_result = imdb[imdb['Director'].isin(long_term_directors)]
longevity_result.groupby(['Director', 'Decade']).size().reset_index(name='Movie_Count')

            Director  Decade  Movie_Count
0     Hayao Miyazaki    1970            1
1     Hayao Miyazaki    1980            4
2     Hayao Miyazaki    1990            2
3     Hayao Miyazaki    2000            3
4     Hayao Miyazaki    2010            1
5    Martin Scorsese    1970            1
6    Martin Scorsese    1980            3
7    Martin Scorsese    1990            2
8    Martin Scorsese    2000            1
9    Martin Scorsese    2010            3
10  Steven Spielberg    1970            2
11  Steven Spielberg    1980            5
12  Steven Spielberg    1990            3
13  Steven Spielberg    2000            2
14  Steven Spielberg    2010            1

In [ ]:
# Ask two questions about this dataset and write your code to answer them.
# Question 1: What are the highest grosing genres?

In [102]:
genre_gross = imdb.groupby('Genre')['Gross'].sum().sort_values(ascending=False)
print('Top 10 highest grossing genres:')
genre_gross.head(10)

Top 10 highest grossing genres:

Genre
Action, Adventure, Sci-Fi       5.898659e+09
Animation, Adventure, Comedy    4.503338e+09
Action, Adventure, Drama        2.668836e+09
Action, Adventure, Fantasy      2.116341e+09
Drama                           2.020898e+09
Animation, Action, Adventure    2.008695e+09
Drama, Romance                  1.962892e+09
Action, Adventure, Comedy       1.920414e+09
Action, Crime, Drama            1.309042e+09
Biography, Drama, History       1.272648e+09
Name: Gross, dtype: float64

In [ ]:
# Questions 2: What are the Actors with the highest gross pay?

In [105]:
actor_gross = imdb.groupby('Star1')['Gross'].sum().sort_values(ascending=False)
actor_gross.head(10)

Star1
Tom Hanks            2.493097e+09
Joe Russo            2.205039e+09
Leonardo DiCaprio    1.877322e+09
Daniel Radcliffe     1.835901e+09
Christian Bale       1.351591e+09
Robert Downey Jr.    1.150720e+09
Elijah Wood          1.035942e+09
Daisy Ridley         9.366622e+08
Mark Hamill          9.223406e+08
Craig T. Nelson      8.700228e+08
Name: Gross, dtype: float64