<a href="https://colab.research.google.com/github/Luca-1221/MyMIS433/blob/main/Copy_of_data_summarization_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise: Data Summarization

In [1]:
import pandas as pd
import numpy as np

In [5]:
pip install nycflights13

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 48.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=88beec0b8576c4e9485cadf5f47269af4ae7cb7c13c85a277ce80fa87b5055c0
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

In [6]:
from nycflights13 import flights
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

## DataFrame with columns

- year,month,day
        Date of departure    
- dep_time,arr_time
        Actual departure and arrival times (format HHMM or HMM), local tz.
- sched_dep_time,sched_arr_time
        Scheduled departure and arrival times (format HHMM or HMM), local tz.    
- dep_delay,arr_delay
        Departure and arrival delays, in minutes. Negative times represent early departures/arrivals.
- hour,minute
        Time of scheduled departure broken into hour and minutes.
- carrier
        Two letter carrier abbreviation. See airlines() to get name
- tailnum
        Plane tail number
- flight
        Flight number
- origin,dest
        Origin and destination. See airports() for additional metadata.
- air_time
        Amount of time spent in the air, in minutes
- distance
        Distance between airports, in miles
- time_hour
        Scheduled date and hour of the flight as a date. Along with origin, can be used to join flights data to weather data.

In [7]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

## Exercises

Write Python scripts to answer the following questions.

In [8]:
# How many distinct airplanes are there in this dataset?

4043

In [10]:
# Which hours of the day are the busiest?
# List the top 5 hours with the most flights.

flights['hour'] = flights['dep_time'] // 100
flights['hour'].value_counts().head(5)

       carrier  flight
1407        EV    4617
1499        WN    2521
1569        WN    2529
1583        EV    4151
25525       OO    8500
26278       US    1226
38024       9E    3283
57452       9E    3297
78484       YV    3799
78964       DL     809
80677       UA     348
81388       WN     217
82160       WN    3032
82581       DL     917
83423       WN    3791
83913       EV    4564
84942       UA    1510
99529       UA     640
101035      9E    3546
103461      DL     462
104224      EV    5015
105044      WN     718
105793      DL    2390
109438      EV    5425
113355      EV    5358
122919      9E    3682
128226      EV    4320
135099      EV    5409
157396      UA     125
159706      B6     205
164597      UA     945
166019      UA     993
168978      UA      18
169531      UA     546
189549      EV    5668
203458      EV    5071
216979      EV    5083
217324      EV    5062
222968      EV    5855
225252      EV    5629
249975      9E    3760
250285      EV    5294
250974      EV    5478
251232      9E    3588
253223      EV    5839
310533      WN     521
310575      EV    6082
310675      WN    1019
310696      EV    5117
310747      DL     390
320397      F9    2001
330040      EV    6093
334398      9E    3583

In [13]:
# Find all flights (identified by 'carrier' and 'flight')
# that always depart at least 60 minutes late.
flights.groupby(['carrier', 'flight']).filter(lambda x: x['dep_delay'].min() >= 60)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
1407,2013,1,2,1548.0,1340,128.0,1710.0,1500,130.0,EV,4617,N10575,EWR,PIT,63.0,319,13,40,2013-01-02T18:00:00Z
1499,2013,1,2,1714.0,1555,79.0,1837.0,1715,82.0,WN,2521,N483WN,EWR,MDW,127.0,711,15,55,2013-01-02T20:00:00Z
1569,2013,1,2,1810.0,1655,75.0,2146.0,2000,106.0,WN,2529,N901WN,EWR,HOU,243.0,1411,16,55,2013-01-02T21:00:00Z
1583,2013,1,2,1829.0,1722,67.0,1940.0,1823,77.0,EV,4151,N15986,EWR,BWI,35.0,169,17,22,2013-01-02T22:00:00Z
25525,2013,1,30,1222.0,1115,67.0,1402.0,1215,107.0,OO,8500,N978SW,LGA,ORD,132.0,733,11,15,2013-01-30T16:00:00Z
26278,2013,1,31,857.0,630,147.0,1111.0,843,148.0,US,1226,N167US,LGA,CLT,104.0,544,6,30,2013-01-31T11:00:00Z
38024,2013,10,12,1809.0,1625,104.0,1957.0,1839,78.0,9E,3283,N292PQ,LGA,CLT,81.0,544,16,25,2013-10-12T20:00:00Z
57452,2013,11,2,1803.0,1603,120.0,1957.0,1827,90.0,9E,3297,N936XJ,LGA,MCI,156.0,1107,16,3,2013-11-02T20:00:00Z
78484,2013,11,25,1258.0,1010,168.0,1415.0,1129,166.0,YV,3799,N511MJ,LGA,IAD,44.0,229,10,10,2013-11-25T15:00:00Z
78964,2013,11,25,2113.0,1615,298.0,19.0,1920,299.0,DL,809,N397DA,EWR,SLC,284.0,1969,16,15,2013-11-25T21:00:00Z
80677,2013,11,27,1724.0,1540,104.0,1850.0,1715,95.0,UA,348,N853UA,EWR,CLE,64.0,404,15,40,2013-11-27T20:00:00Z
81388,2013,11,28,1250.0,935,195.0,1359.0,1115,164.0,WN,217,N914WN,LGA,MDW,111.0,725,9,35,2013-11-28T14:00:00Z
82160,2013,11,29,1800.0,1630,90.0,2041.0,1940,61.0,WN,3032,N470WN,EWR,HOU,201.0,1411,16,30,2013-11-29T21:00:00Z
82581,2013,11,30,1052.0,815,157.0,1255.0,1042,133.0,DL,917,N319NB,LGA,DEN,216.0,1620,8,15,2013-11-30T13:00:00Z
83423,2013,12,1,941.0,710,151.0,1105.0,855,130.0,WN,3791,N7730A,EWR,STL,128.0,872,7,10,2013-12-01T12:00:00Z
83913,2013,12,1,1818.0,1647,91.0,2021.0,1807,134.0,EV,4564,N14950,EWR,ROC,47.0,246,16,47,2013-12-01T21:00:00Z
84942,2013,12,2,1823.0,1345,278.0,2123.0,1640,283.0,UA,1510,N75861,EWR,IAH,186.0,1400,13,45,2013-12-02T18:00:00Z
99529,2013,12,18,1704.0,1509,115.0,1933.0,1742,111.0,UA,640,N412UA,LGA,DEN,237.0,1620,15,9,2013-12-18T20:00:00Z
101035,2013,12,20,914.0,810,64.0,1050.0,950,60.0,9E,3546,N604LR,LGA,RIC,65.0,292,8,10,2013-12-20T13:00:00Z
103461,2013,12,22,2300.0,2055,125.0,10.0,2213,117.0,DL,462,N973DL,JFK,BOS,37.0,187,20,55,2013-12-23T01:00:00Z
104224,2013,12,23,1834.0,1529,185.0,2100.0,1808,172.0,EV,5015,N615QX,LGA,IND,113.0,660,15,29,2013-12-23T20:00:00Z
105044,2013,12,24,1703.0,1545,78.0,1915.0,1825,50.0,WN,718,N770SA,EWR,MSY,175.0,1167,15,45,2013-12-24T20:00:00Z
105793,2013,12,25,1817.0,1645,92.0,2127.0,2010,77.0,DL,2390,N962DL,LGA,RSW,163.0,1080,16,45,2013-12-25T21:00:00Z
109438,2013,12,29,2042.0,1940,62.0,2241.0,2206,35.0,EV,5425,N840AS,LGA,CAE,100.0,617,19,40,2013-12-30T00:00:00Z
110188,2013,12,30,1632.0,1529,63.0,1842.0,1808,34.0,EV,5015,N371CA,LGA,IND,109.0,660,15,29,2013-12-30T20:00:00Z
113355,2013,2,3,1545.0,1427,78.0,1714.0,1624,50.0,EV,5358,N600QX,LGA,MSN,121.0,812,14,27,2013-02-03T19:00:00Z
122919,2013,2,14,1131.0,1025,66.0,1322.0,1231,51.0,9E,3682,N8946A,EWR,DTW,87.0,488,10,25,2013-02-14T15:00:00Z
128226,2013,2,20,955.0,820,95.0,1148.0,1017,91.0,EV,4320,N13914,EWR,DAY,89.0,533,8,20,2013-02-20T13:00:00Z
134587,2013,2,27,1001.0,820,101.0,1239.0,1017,142.0,EV,4320,N26549,EWR,DAY,88.0,533,8,20,2013-02-27T13:00:00Z
135099,2013,2,27,1947.0,1820,87.0,2124.0,2003,81.0,EV,5409,N710EV,LGA,MSN,121.0,812,18,20,2013-02-27T23:00:00Z
136238,2013,2,28,NaN,1820,NaN,NaN,2003,NaN,EV,5409,N740EV,LGA,MSN,NaN,812,18,20,2013-02-28T23:00:00Z
157396,2013,3,23,1650.0,1521,89.0,1940.0,1747,113.0,UA,125,N37298,LGA,DEN,253.0,1620,15,21,2013-03-23T19:00:00Z
159706,2013,3,26,827.0,705,82.0,1131.0,1025,66.0,B6,205,N559JB,JFK,LGB,335.0,2465,7,5,2013-03-26T11:00:00Z
164597,2013,3,31,1422.0,1320,62.0,1724.0,1630,54.0,UA,945,N418UA,EWR,LAX,345.0,2454,13,20,2013-03-31T17:00:00Z
166019,2013,4,1,2213.0,2104,69.0,54.0,2359,55.0,UA,993,N844UA,EWR,IAH,199.0,1400,21,4,2013-04-02T01:00:00Z
168978,2013,4,4,2130.0,1955,95.0,43.0,2327,76.0,UA,18,N17229,EWR,SFO,341.0,2565,19,55,2013-04-04T23:00:00Z
169531,2013,4,5,1450.0,1350,60.0,1813.0,1657,76.0,UA,546,N822UA,EWR,FLL,170.0,1065,13,50,2013-04-05T17:00:00Z
169980,2013,4,5,2219.0,2104,75.0,54.0,2359,55.0,UA,993,N816UA,EWR,IAH,189.0,1400,21,4,2013-04-06T01:00:00Z
170279,2013,4,6,1133.0,1000,93.0,1426.0,1310,76.0,UA,348,N483UA,EWR,RSW,153.0,1068,10,0,2013-04-06T14:00:00Z
189549,2013,4,26,1813.0,1627,106.0,2017.0,1824,113.0,EV,5668,N14974,EWR,DAY,91.0,533,16,27,2013-04-26T20:00:00Z
203458,2013,5,11,1932.0,1800,92.0,2031.0,1930,61.0,EV,5071,N391CA,LGA,BTV,39.0,258,18,0,2013-05-11T22:00:00Z
216979,2013,5,26,1418.0,1240,98.0,1603.0,1434,89.0,EV,5083,N755EV,EWR,DTW,78.0,488,12,40,2013-05-26T16:00:00Z
217324,2013,5,26,2106.0,1915,111.0,2208.0,2047,81.0,EV,5062,N760EV,LGA,BTV,42.0,258,19,15,2013-05-26T23:00:00Z
222968,2013,6,2,128.0,2159,209.0,325.0,10,195.0,EV,5855,N13553,EWR,SDF,101.0,642,21,59,2013-06-03T01:00:00Z
225252,2013,6,4,1211.0,1100,71.0,1444.0,1245,119.0,EV,5629,N713EV,LGA,XNA,154.0,1147,11,0,2013-06-04T15:00:00Z
249975,2013,6,30,1447.0,1110,217.0,1728.0,1240,288.0,9E,3760,N819AY,JFK,RIC,58.0,288,11,10,2013-06-30T15:00:00Z
250285,2013,6,30,2142.0,1830,192.0,2319.0,2045,154.0,EV,5294,N748EV,EWR,DTW,76.0,488,18,30,2013-06-30T22:00:00Z
250974,2013,7,1,1544.0,1142,242.0,1717.0,1336,221.0,EV,5478,N754EV,LGA,GSO,73.0,461,11,42,2013-07-01T15:00:00Z
251232,2013,7,1,2034.0,1839,115.0,2158.0,2029,89.0,9E,3588,N8888D,JFK,ORF,50.0,290,18,39,2013-07-01T22:00:00Z
253223,2013,7,3,2035.0,1930,65.0,2324.0,2201,83.0,EV,5839,N13995,EWR,ATL,117.0,746,19,30,2013-07-03T23:00:00Z
310533,2013,9,2,1846.0,1300,346.0,2000.0,1425,335.0,WN,521,N459WN,EWR,BNA,107.0,748,13,0,2013-09-02T17:00:00Z
310575,2013,9,2,1928.0,1655,153.0,2106.0,1814,172.0,EV,6082,N16571,EWR,RIC,54.0,277,16,55,2013-09-02T20:00:00Z
310675,2013,9,2,2148.0,1825,203.0,2317.0,2000,197.0,WN,1019,N292WN,LGA,BNA,110.0,764,18,25,2013-09-02T22:00:00Z
310696,2013,9,2,2209.0,1830,219.0,48.0,2045,243.0,EV,5117,N538CA,EWR,DTW,99.0,488,18,30,2013-09-02T22:00:00Z
310747,2013,9,2,2319.0,1745,334.0,132.0,2014,318.0,DL,390,N372NW,LGA,DEN,210.0,1620,17,45,2013-09-02T21:00:00Z
320397,2013,9,13,905.0,800,65.0,1114.0,1020,54.0,F9,2001,N208FR,LGA,DEN,210.0,1620,8,0,2013-09-13T12:00:00Z
330040,2013,9,23,1807.0,1559,128.0,1957.0,1750,127.0,EV,6093,N11192,EWR,AVL,85.0,583,15,59,2013-09-23T19:00:00Z
334398,2013,9,28,952.0,817,95.0,1150.0,1021,89.0,9E,3583,N8554A,JFK,DTW,77.0,509,8,17,2013-09-28T12:00:00Z

In [19]:
# Find all United Airlines (UA) flights (identified by 'carrier' and 'flight')
# that depart (at least) 60 minutes late.
flights[(flights['carrier'] == 'UA') & (flights['dep_delay'] >= 60)]

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
218,2013,1,1,957.0,733,144.0,1056.0,853,123.0,UA,856,N534UA,EWR,BOS,37.0,200,7,33,2013-01-01T12:00:00Z
268,2013,1,1,1114.0,900,134.0,1447.0,1222,145.0,UA,1086,N76502,LGA,IAH,248.0,1416,9,0,2013-01-01T14:00:00Z
526,2013,1,1,1607.0,1443,84.0,1711.0,1553,78.0,UA,465,N435UA,EWR,BOS,35.0,200,14,43,2013-01-01T19:00:00Z
1032,2013,1,2,833.0,558,155.0,1018.0,727,171.0,UA,651,N448UA,EWR,ORD,129.0,719,5,58,2013-01-02T10:00:00Z
1310,2013,1,2,1412.0,838,334.0,1710.0,1147,323.0,UA,468,N474UA,EWR,MCO,150.0,937,8,38,2013-01-02T13:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
335264,2013,9,29,1336.0,1144,112.0,1611.0,1429,102.0,UA,1519,N21108,EWR,MCO,128.0,937,11,44,2013-09-29T15:00:00Z
335317,2013,9,29,1435.0,1226,129.0,1552.0,1338,134.0,UA,252,N431UA,EWR,BOS,33.0,200,12,26,2013-09-29T16:00:00Z
335561,2013,9,29,1801.0,1625,96.0,2023.0,1841,102.0,UA,485,N526UA,EWR,DEN,205.0,1605,16,25,2013-09-29T20:00:00Z
336027,2013,9,30,858.0,659,119.0,1139.0,955,104.0,UA,537,N421UA,EWR,PBI,130.0,1023,6,59,2013-09-30T10:00:00Z
336762,2013,9,30,2233.0,2113,80.0,112.0,30,42.0,UA,471,N578UA,EWR,SFO,318.0,2565,21,13,2013-10-01T01:00:00Z

In [21]:
# How many United Airlines (UA) flights depart (at least) 60 minutes late?
ua_late_flights = flights[(flights['carrier'] == 'UA') & (flights['dep_delay'] >= 60)]
ua_late_flights.shape[0]

3899

In [23]:
# Which flights that always arrived on time in December?
flights[flights['month'] == 12].groupby(['carrier', 'flight']).filter(lambda x: x['arr_delay'].max() <= 0)

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
83164,2013,12,1,520.0,515,5.0,749.0,808,-19.0,UA,1487,N69804,EWR,IAH,193.0,1400,5,15,2013-12-01T10:00:00Z
83168,2013,12,1,546.0,545,1.0,826.0,835,-9.0,UA,1441,N23708,LGA,IAH,204.0,1416,5,45,2013-12-01T10:00:00Z
83174,2013,12,1,554.0,600,-6.0,645.0,705,-20.0,US,1739,N947UW,LGA,PHL,36.0,96,6,0,2013-12-01T11:00:00Z
83175,2013,12,1,555.0,600,-5.0,805.0,827,-22.0,DL,1377,N386DA,LGA,ATL,112.0,762,6,0,2013-12-01T11:00:00Z
83177,2013,12,1,556.0,600,-4.0,742.0,756,-14.0,DL,1517,N332NB,EWR,DTW,87.0,488,6,0,2013-12-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111156,2013,12,31,1812.0,1815,-3.0,1910.0,1936,-26.0,EV,5003,N724EV,LGA,SYR,41.0,198,18,15,2013-12-31T23:00:00Z
111164,2013,12,31,1821.0,1808,13.0,2142.0,2153,-11.0,UA,577,N808UA,EWR,PHX,301.0,2133,18,8,2013-12-31T23:00:00Z
111216,2013,12,31,1936.0,1945,-9.0,2048.0,2120,-32.0,9E,2950,N8516C,JFK,BWI,39.0,184,19,45,2014-01-01T00:00:00Z
111227,2013,12,31,2001.0,1959,2.0,2248.0,2303,-15.0,UA,469,N417UA,EWR,PBI,145.0,1023,19,59,2014-01-01T00:00:00Z
111233,2013,12,31,2019.0,2033,-14.0,2144.0,2206,-22.0,FL,1544,N974AT,LGA,CAK,74.0,397,20,33,2014-01-01T01:00:00Z

In [24]:
# How many flights always arrived on time in December?
dec_on_time = flights[flights['month'] == 12].groupby(['carrier', 'flight']).filter(lambda x: x['arr_delay'].max() <= 0)
dec_on_time.shape[0]

552

In [26]:
# Create a dataframe 'cancelled' for all cancelled flights.
# Assumption: flights that are not cancelled should have values for dep_time.
cancelled = flights[flights['dep_time'].isna()].copy()

In [30]:
# Look at the number of cancelled flights per day.
# Find the top 10 days with the most cancelled flights.
cancelled.groupby(['year', 'month', 'day']).size().sort_values(ascending=False).head(10)

year  month  day
2013  2      8      472
             9      393
      5      23     221
      12     10     204
      9      12     192
      3      6      180
             8      180
      12     5      158
             14     125
      6      28     123
dtype: int64

In [31]:
# Which carrier has the worst average arrival delay?
flights.groupby('carrier')['arr_delay'].mean().sort_values(ascending=False).head(1)

carrier
F9    21.920705
Name: arr_delay, dtype: float64

In [32]:
# Which plane (tailnum) has the worst on-time record?
flights.groupby('tailnum')['arr_delay'].mean().sort_values(ascending=False).head(1)

tailnum
N844MH    320.0
Name: arr_delay, dtype: float64

In [33]:
# What time (hour) of day should you fly if you want to avoid delays as much as possible?
flights.groupby('hour')['dep_delay'].mean().sort_values(ascending=False).head(1)

hour
19    24.784791
Name: dep_delay, dtype: float64

In [34]:
# For each destination, compute the total minutes of arrival delay.
flights.groupby('dest')['arr_delay'].sum()

dest
ABQ      1113.0
ACK      1281.0
ALB      6018.0
ANC       -20.0
ATL    190260.0
         ...
TPA     54749.0
TUL      9896.0
TVC      1232.0
TYS     13912.0
XNA      7406.0
Name: arr_delay, Length: 105, dtype: float64

In [37]:
# Find the worst days in terms of average arrival delay greater than 1 hour.
daily_avg=flights.groupby(['year', 'month', 'day'])['arr_delay'].mean()
daily_avg[daily_avg > 60]

year  month  day
2013  3      8      85.862155
      5      23     61.970899
      6      13     63.753689
      7      22     62.763403
Name: arr_delay, dtype: float64

In [38]:
# Find the number of carriers between each pair of origin and destination.
flights.groupby(['origin', 'dest'])['carrier'].nunique()
#

origin  dest
EWR     ALB     1
        ANC     1
        ATL     4
        AUS     2
        AVL     1
               ..
LGA     SYR     2
        TPA     2
        TVC     2
        TYS     1
        XNA     2
Name: carrier, Length: 224, dtype: int64